version: '3.0'

services:
  jenkins-nginx:
    image: nginx:mainline-alpine
    container_name: jenkins-nginx
    depends_on:
      - jenkins-blueocean
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9000:9000
    networks:
      - jenkins-robert
    restart: on-failure

  jenkins-blueocean:
    image: jenkins-blueocean
    container_name: jenkins-blueocean
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 49000:49000
      - 50000:50000
    networks:
      - jenkins-robert
    restart: on-failure
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - $HOME:/home
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS="-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
      - JENKINS_OPTS="--httpPort=49000"
  
  jenkis-docker: 
    image: docker:dind
    container_name: jenkins-docker
    networks:
      jenkins-robert: 
        aliases: 
          - docker
    ports:
      - 2376:2376
      - 3000:3000
    volumes:
      - jenkins-docker-certs:/certs/client 
      - jenkins-data:/var/jenkins_home 
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs

volumes:
  jenkins-data:
    name: jenkins-data

  jenkins-docker-certs:
    name: jenkins-docker-certs

networks:
  jenkins-robert:
    driver: bridge
