version: "3.8"
services:
  jenkins-docker:
    container_name: jenkins_docker
    image: docker:dind
    restart: always
    privileged: true
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
      - "3000:3000"
    command: --storage-driver overlay2
  jenkins-blueocean:
    container_name: jenkins_blueocean
    build: jenkins
    restart: on-failure
    depends_on:
      - jenkins-docker
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://jenkins-docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    networks:
      - jenkins
    depends_on:
      - jenkins-blueocean
    volumes:
      - "./nginx/:/etc/nginx/conf.d/"
    ports:
      - "9000:9000"
networks:
  jenkins:
volumes:
  jenkins-docker-certs:
  jenkins-data:
